#!/usr/bin/env python3
"""Generate root README summary from per-problem README metadata."""
import re
from pathlib import Path
from collections import defaultdict, Counter


ROOT = Path(__file__).resolve().parents[1]
MARKER_START = '<!-- GENERATED-README:START -->'
MARKER_END = '<!-- GENERATED-README:END -->'
LEETCODE_TOP_RE = re.compile(r'^\d+-')
ORGANIZED_PARENTS = ('Array', 'Data Structures & Algorithms')


def parse_difficulty(text: str, readme_path: Path) -> str:
    """Extract difficulty from LeetCode badges, GFG headings, or folder path."""
    for pattern in (
        r"alt=['\"]Difficulty[:\- ]*([A-Za-z]+)['\"]",
        r'badge-Difficulty-([A-Za-z]+)',
        r'Difficulty Level\s*:\s*Difficulty:\s*(\w+)',
        r'Difficulty:\s*(\w+)',
    ):
        m = re.search(pattern, text, re.I)
        if m:
            return m.group(1).strip().capitalize()

    for part in readme_path.relative_to(ROOT).parts:
        if part.startswith('Difficulty:'):
            return part.split(':', 1)[1].strip()

    return 'Unknown'


def should_skip(readme_path: Path) -> bool:
    rel = readme_path.parent.relative_to(ROOT)
    if len(rel.parts) != 1:
        return False
    slug = rel.parts[0]
    if not LEETCODE_TOP_RE.match(slug):
        return False
    return any((ROOT / parent / slug).is_dir() for parent in ORGANIZED_PARENTS)


def topic_for(readme_path: Path) -> str:
    rel = readme_path.parent.relative_to(ROOT)
    top = rel.parts[0]
    if len(rel.parts) == 1 and LEETCODE_TOP_RE.match(top):
        return 'LeetCode'
    return top


def parse_problem(readme_path: Path):
    text = readme_path.read_text(encoding='utf8')
    # title and url
    m = re.search(r'<h2>\s*<a\s+href="([^"]+)">([^<]+)</a>\s*</h2>', text)
    if m:
        url = m.group(1).strip()
        title = m.group(2).strip()
    else:
        # fallback: first markdown heading
        m2 = re.search(r'^#\s+(.+)', text, re.MULTILINE)
        title = m2.group(1).strip() if m2 else readme_path.parent.name
        url = ''

    d = parse_difficulty(text, readme_path)

    # languages
    exts = set()
    for p in readme_path.parent.iterdir():
        if p.name.lower() == 'readme.md':
            continue
        if p.is_file():
            exts.add(p.suffix.lower())
    if exts:
        lang_map = {
            '.py': 'Python', '.cpp': 'C++', '.c': 'C', '.java': 'Java', '.js': 'JavaScript',
            '.ts': 'TypeScript', '.go': 'Go', '.rs': 'Rust'
        }
        langs = [lang_map.get(e, e.lstrip('.').upper()) for e in sorted(exts)]
        lang = ' / '.join(langs)
    else:
        lang = '—'

    rel = readme_path.parent.relative_to(ROOT).as_posix()
    return {
        'title': title,
        'url': url,
        'difficulty': d,
        'lang': lang,
        'path': rel,
    }


def collect_problems():
    problems = defaultdict(list)
    all_items = []
    seen_paths = set()
    for md in sorted(ROOT.rglob('README.md')):
        if md.parent == ROOT or should_skip(md):
            continue
        rel = md.parent.relative_to(ROOT).as_posix()
        if rel in seen_paths:
            continue
        try:
            item = parse_problem(md)
        except Exception:
            continue
        seen_paths.add(rel)
        topic = topic_for(md)
        problems[topic].append(item)
        all_items.append(item)
    return problems, all_items


def render(problems, all_items):
    total = len(all_items)
    diff_counts = Counter([p['difficulty'] for p in all_items])

    lines = []
    lines.append('# DSA_Practice — Auto-generated summary')
    lines.append('')
    lines.append(f'- Total problems discovered: **{total}**')
    lines.append(f'- Difficulty: ' + ', '.join(f'**{k}**: {v}' for k, v in diff_counts.items()))
    lines.append('')
    lines.append('---')

    for topic in sorted(problems.keys()):
        lines.append(f'## {topic}')
        lines.append('')
        lines.append('| Problem | Difficulty | Language | Link |')
        lines.append('|---|---:|---|---|')
        for p in sorted(problems[topic], key=lambda x: x['title'].lower()):
            title = p['title']
            diff = p['difficulty']
            lang = p['lang']
            path = p['path']
            link = f'[{title}]({path})'
            lines.append(f'| {title} | {diff} | {lang} | {link} |')
        lines.append('')

    lines.append('---')
    lines.append('*Generated by `scripts/generate_readme.py`.*')
    return '\n'.join(lines)


def main():
    problems, all_items = collect_problems()
    content = render(problems, all_items)

    readme_path = ROOT / 'README.md'
    text = readme_path.read_text(encoding='utf8')
    if MARKER_START in text and MARKER_END in text:
        before, rest = text.split(MARKER_START, 1)
        _, after = rest.split(MARKER_END, 1)
        new_text = before + MARKER_START + '\n' + content + '\n' + MARKER_END + after
    else:
        new_text = text + '\n' + MARKER_START + '\n' + content + '\n' + MARKER_END + '\n'

    readme_path.write_text(new_text, encoding='utf8')
    print(f'Wrote {readme_path} ({len(all_items)} problems)')


if __name__ == '__main__':
    main()
