#!/usr/bin/env python3
"""Generate root README summary from per-problem README metadata."""
import re
from pathlib import Path
from collections import defaultdict, Counter


ROOT = Path(__file__).resolve().parents[1]
MARKER_START = '<!-- GENERATED-README:START -->'
MARKER_END = '<!-- GENERATED-README:END -->'


def parse_problem(readme_path: Path):
    text = readme_path.read_text(encoding='utf8')
    # title and url
    m = re.search(r'<h2>\s*<a\s+href="([^"]+)">([^<]+)</a>\s*</h2>', text)
    if m:
        url = m.group(1).strip()
        title = m.group(2).strip()
    else:
        # fallback: first markdown heading
        m2 = re.search(r'^#\s+(.+)', text, re.MULTILINE)
        title = m2.group(1).strip() if m2 else readme_path.parent.name
        url = ''

    # difficulty
    d = None
    m = re.search(r"alt=[\'\"]Difficulty[:\- ]*([A-Za-z]+)[\'\"]", text)
    if not m:
        m = re.search(r'badge-Difficulty-([A-Za-z]+)', text)
    if m:
        d = m.group(1)
    else:
        m = re.search(r'\bDifficulty\s*[:\-]?\s*([A-Za-z]+)\b', text)
        d = m.group(1) if m else 'Unknown'

    # languages
    exts = set()
    for p in readme_path.parent.iterdir():
        if p.name.lower() == 'readme.md':
            continue
        if p.is_file():
            exts.add(p.suffix.lower())
    if exts:
        lang_map = {
            '.py': 'Python', '.cpp': 'C++', '.c': 'C', '.java': 'Java', '.js': 'JavaScript',
            '.ts': 'TypeScript', '.go': 'Go', '.rs': 'Rust'
        }
        langs = [lang_map.get(e, e.lstrip('.').upper()) for e in sorted(exts)]
        lang = ' / '.join(langs)
    else:
        lang = '—'

    rel = readme_path.parent.relative_to(ROOT).as_posix()
    return {
        'title': title,
        'url': url,
        'difficulty': d,
        'lang': lang,
        'path': rel,
    }


def collect_problems():
    problems = defaultdict(list)
    all_items = []
    # Top-level folders to exclude from generated listing
    EXCLUDE_TOP = {'1-two-sum'}
    for md in ROOT.rglob('README.md'):
        if md.parent == ROOT:
            continue
        try:
            item = parse_problem(md)
        except Exception:
            continue
        top = md.parent.relative_to(ROOT).parts[0]
        if top in EXCLUDE_TOP:
            continue
        problems[top].append(item)
        all_items.append(item)
    return problems, all_items


def render(problems, all_items):
    total = len(all_items)
    diff_counts = Counter([p['difficulty'] for p in all_items])

    lines = []
    lines.append('# DSA_Practice — Auto-generated summary')
    lines.append('')
    lines.append(f'- Total problems discovered: **{total}**')
    lines.append(f'- Difficulty: ' + ', '.join(f'**{k}**: {v}' for k, v in diff_counts.items()))
    lines.append('')
    lines.append('---')

    for topic in sorted(problems.keys()):
        lines.append(f'## {topic}')
        lines.append('')
        lines.append('| Problem | Difficulty | Language | Link |')
        lines.append('|---|---:|---|---|')
        for p in sorted(problems[topic], key=lambda x: x['title'].lower()):
            title = p['title']
            diff = p['difficulty']
            lang = p['lang']
            path = p['path']
            link = f'[{title}]({path})'
            lines.append(f'| {title} | {diff} | {lang} | {link} |')
        lines.append('')

    lines.append('---')
    lines.append('*Generated by `scripts/generate_readme.py`.*')
    return '\n'.join(lines)


def main():
    problems, all_items = collect_problems()
    content = render(problems, all_items)

    readme_path = ROOT / 'README.md'
    text = readme_path.read_text(encoding='utf8')
    if MARKER_START in text and MARKER_END in text:
        before, rest = text.split(MARKER_START, 1)
        _, after = rest.split(MARKER_END, 1)
        new_text = before + MARKER_START + '\n' + content + '\n' + MARKER_END + after
    else:
        new_text = text + '\n' + MARKER_START + '\n' + content + '\n' + MARKER_END + '\n'

    readme_path.write_text(new_text, encoding='utf8')
    print(f'Wrote {readme_path} ({len(all_items)} problems)')


if __name__ == '__main__':
    main()
